### PR TITLE
Room game functionalities

### LINKED ISSUE #27: Question set generation (room)
Need to create some kind of manager to generate question sets on the run. Daily challenges are ad hoc cases that can either use this manager or being manually set up.

### LINKED ISSUE #33: Submit the answer to the server for verification

### LINKED ISSUE #35: Request questions from the server

### LINKED ISSUE #37: Timeout bar to see how much time is used

### PR DESCRIPTION
**Pull request by AnoldGH**
Components & utilities necessary to hold room games

As of now, we have functionalities to
  - create room
  - join room
  - fetch other users (userId & scores)
  - save room records to database
  - generate question sets (resolves #27 )
  - request question sets from servers (resolves #35 )
  - submit answers to the server side
  - server-side verification (resolves #33 )
  - timeout (resolves #37)
  - progress tracking (to the level question index)
  - automatic freeup

Part of both #4 and #5

### CODE REVIEW

**Review by Hakob3215 — CHANGES_REQUESTED** [review]
in room.js, I feel as though you should remove the test function call

**Comment by AnoldGH** [comment]
> in room.js, I feel as though you should remove the test function call

Good catch, will piggyback it in the next commit

**Comment by AnoldGH** [comment]
> in room.js, I feel as though you should remove the test function call

test() is now commented out

**Review by Hakob3215 — APPROVED** [review]
LGTM now, nice changes

**Review by MichaelPeng123 — APPROVED** [review]
lgtm

**Pull request merged**
